# Generated by Django 5.0.4 on 2024-04-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsdev', '0002_alter_college_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='colleges',
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
